### ISSUE TITLE
Show "choose username" UI on first startup

### ISSUE THREAD

**Issue by Tostifrosti** [TotemArts/Launcher#1]
The latest release (0.3) contains a RenegadeX-Launcher.ini config file with the PlayerName set to 'SonnyX'. 

Just an idea: Maybe it's nice to ask the user for their username when they start the launcher for the first time?

**Comment by SonnyX** [comment]
Unimplemented intended feature is that if the username is missing in the .ini the launcher shows an popup/overlay to enter an username. this popup/overlay should not have any cancel or exit button.
