### ISSUE TITLE
License

### ISSUE THREAD

**Issue by meteorsnows** [TotemArts/Launcher#13]
Great Repo. Could you consider open source in more permissible license, 
so people could use learn more well how to use Sciter instead of Electron?

**Comment by SonnyX** [comment]
You should feel free to use the code in any way you like, art-assets and pictures however aren't mine and should thus be only used in relation to the RenegadeX project or other projects that may come from TotemArts in the future.
I'm not too familiar with the different licenses though, so any suggestions are welcome.

**Comment by meteorsnows** [comment]
Thanks for good news. MIT, BSD 2 clause, Apache are extremely permissive. No warranty and obligation from author but allow people to reuse the code in closed/open source. Apache license require other to publish changes they made on every file derived from Author. 
But they can bypass it by writing wrapper, but good to learn how other making reusable library, if you open source high reusable utilities code.

I am guessing your work is most suitable in following settings: The following popular learn code from game's project in the github using MIT for code, and disclaimer the Art is CC. 
[CodeCombat](https://github.com/codecombat/codecombat)
