### ISSUE TITLE
Crash: Click on multiplayer during update

### ISSUE THREAD

**Issue by Tostifrosti** [TotemArts/Launcher#2]
I don't know how, but I managed to crash the launcher on my first time xD
The launcher asked me to update to the latest version. During the update, the buttons on top were still clickable. So, as a developer/tester/retard I pressed the 'multiplayer' button and managed to crash to Launcher.

Idea: Maybe disable all buttons on top when updating the game?

![new-rx-launcher-crash](https://user-images.githubusercontent.com/3437899/55289873-5b32cb00-53cc-11e9-931b-56c129a39c3b.PNG)

**Comment by SonnyX** [comment]
Correct, caused since we used to have a separate screen for the update/download screen,
I'll fix it in the next commit

**Comment by SonnyX** [comment]
Disabled menu-buttons in 16c3013
