### ISSUE TITLE
Error while installing the game

### ISSUE THREAD

**Issue by podliva1337** [TotemArts/Launcher#20]
After the start launcher says "An error has occurred while "Installing game", the error states: </p><p>Couldn't fetch instructions.json"

I've made some digging and found that launcher loads version info from this link:
https://static.renegade-x.com/launcher_data/version/launcher.json -
That in return responses PATCH5400A as game current version, but all of the update servers returns 404 error for this patch.

Correct version/link (for now) is:
http://rxp-lv.cncirc.net/PATCH5440B/

So. Actually i'm in doubt that this is the right place for this issue, but don't know where to address it.

**Comment by SonnyX** [comment]
Should be fixed now.
